# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05ed9333797254553d4591d50c92cff126793d49079abf659161ece9e8c400a55666297f8c17db38f243604b405020c5f1e7c44c88a10b39d6b65495e3804335

test:
  secret_key_base: 2495dfffc8f8ddbc895f811c0941e6cde92b8f552675ccfc4c87b09368603fdb34a495a75a8b5bff66feed5bbcbe5c366e5e8f82964c81631e90fbcc3047be79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
